/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package artifical_ıntelligence;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Random;
import javax.swing.JButton;

/**
 *
 * @author Feyza Nur Saka
 */
public class aToyProblem extends javax.swing.JFrame {

    JButton[] x = new JButton[9];
    ArrayList<Integer> temp = new ArrayList<>();

    /**
     * Creates new form aToyProblem
     */
    public aToyProblem() {
        initComponents();

        x[0] = jButton1;
        x[1] = jButton2;
        x[2] = jButton3;
        x[3] = jButton4;
        x[4] = jButton5;
        x[5] = jButton6;
        x[6] = jButton7;
        x[7] = jButton8;
        x[8] = jButton9;

        ArrayList numbers = new ArrayList();
        for (int i = 0; i < 9; i++) {
            numbers.add(i);
        }
        numbers.set(0, 0);
        Collections.shuffle(numbers);
        for (int i = 0; i < x.length; i++) {
            x[i].setText(numbers.get(i) + "");
        }
        String temp = x[4].getText();
        int index = 0;

        for (int i = 0; i < x.length; i++) {
            if (x[i].getText().endsWith("0")) {
                index = i;
            }
        }
        x[index].setText(temp);
        x[4].setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("1");

        jButton2.setText("2");

        jButton3.setText("4");

        jButton4.setText("3");

        jButton5.setText("0");

        jButton6.setText("8");

        jButton7.setText("7");

        jButton8.setText("6");

        jButton9.setText("5");

        jButton10.setText("^");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("v");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("<");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText(">");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton13)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton10)
                                    .addComponent(jButton12))
                                .addGap(27, 27, 27)
                                .addComponent(jButton11)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("");
        int i = 0;
        int index = 0;
        String temp = "";
        for (JButton xn : x) {
            if (xn.getText() == "0") {
                if (i != 0 && i != 1 && i != 2) {
                    System.out.println("^");
                    index = i - 3;
                    System.out.println("0 ın olduğu index = " + i);
                    temp = x[index].getText();
                    x[index].setText("0");
                    // System.out.println("değiştikten sonra 0 = " + x[index].getText());
                    xn.setText(temp);
                    System.out.println("0'la yerini değiştiren sayı = " + xn.getText());
                    System.out.println("----------------------------------------------");
                    break;
                } else {
                    jLabel1.setText("yanlış hamle");
                }
            }
            i++;
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("");
        int i = 0;
        int index = 0;
        String temp = "";
        for (JButton xn : x) {
            if (xn.getText() == "0") {
                if (i != 6 && i != 7 && i != 8) {
                    System.out.println("v");
                    index = i + 3;
                    System.out.println("0 ın olduğu index = " + i);
                    temp = x[index].getText();
                    x[index].setText("0");
                    // System.out.println("değiştikten sonra 0 = " + x[index].getText());
                    xn.setText(temp);
                    System.out.println("0'la yerini değiştiren sayı = " + xn.getText());
                    System.out.println("----------------------------------------------");
                    break;
                } else {
                    jLabel1.setText("yanlış hamle");
                }
            }
            i++;
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("");
        int i = 0;
        int index = 0;
        String temp = "";
        for (JButton xn : x) {
            if (xn.getText() == "0") {
                if (i != 2 && i != 5 && i != 8) {
                    System.out.println(">");
                    index = i + 1;
                    System.out.println("0 ın olduğu index = " + i);
                    temp = x[index].getText();
                    x[index].setText("0");
                    // System.out.println("değiştikten sonra 0 = " + x[index].getText());
                    xn.setText(temp);
                    System.out.println("0'la yerini değiştiren sayı = " + xn.getText());
                    System.out.println("----------------------------------------------");
                    break;
                } else {
                    jLabel1.setText("yanlış hamle");
                }
            }
            i++;
        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("");
        int i = 0;
        int index = 0;
        String temp = "";
        for (JButton xn : x) {
            if (xn.getText() == "0") {
                if (i != 0 && i != 3 && i != 6) {
                    System.out.println("<");
                    index = i - 1;
                    System.out.println("0 ın olduğu index = " + i);
                    temp = x[index].getText();
                    x[index].setText("0");
                    //System.out.println("değiştikten sonra 0 = " + x[index].getText());
                    xn.setText(temp);
                    System.out.println("0'la yerini değiştiren sayı = " + xn.getText());
                    System.out.println("----------------------------------------------");
                    break;
                } else {
                    jLabel1.setText("yanlış hamle");
                }
            }
            i++;
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aToyProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aToyProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aToyProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aToyProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aToyProblem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
